# Generated by Django 3.1.7 on 2021-03-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_schoolclass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolClass',
            new_name='ClassRoom',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='name',
            new_name='room_no',
        ),
    ]
